#!/bin/bash -e

case "$1" in
    remove | purge)
        STATE_DIR="/var/lib/pi-top-usb-setup"
        if [ -d "$STATE_DIR" ]; then
            echo "Removing state directory in $STATE_DIR"
            rm -rf "$STATE_DIR"
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
